# Generated by Django 3.1.5 on 2021-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPasien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasien',
            name='no_pasien',
            field=models.CharField(default='-', max_length=7),
        ),
        migrations.AddField(
            model_name='datapasien',
            name='no_telepon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='alamat',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='kota',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='nama',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
