# Generated by Django 3.1.5 on 2021-01-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPasien', '0002_auto_20210107_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapasien',
            name='alamat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='kota',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='nama',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='no_pasien',
            field=models.CharField(max_length=7),
        ),
    ]
